package com.sangtao.dao;

import com.sangtao.model.CompanyRelation;

import java.util.List;

public interface CompanyRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_company_relation
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    int insert(CompanyRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_company_relation
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    List<CompanyRelation> selectAll();
}