package com.sangtao.dao;

import com.sangtao.model.SysResources;

import java.util.List;

public interface SysResourcesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    int deleteByPrimaryKey(String sysResourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    int insert(SysResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    SysResources selectByPrimaryKey(String sysResourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    List<SysResources> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    int updateByPrimaryKey(SysResources record);
}