package com.sangtao.dao;

import com.sangtao.model.UserRole;

import java.util.List;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    List<UserRole> selectAll();
}