package com.sangtao.model;

import java.util.Date;

public class AccountInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account_info.sub_account_id
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    private String subAccountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account_info.account_id
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account_info.account_phone
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    private String accountPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account_info.sub_account_type
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    private String subAccountType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account_info.account_status
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    private String accountStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account_info.create_time
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account_info.create_user
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account_info.update_time
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account_info.update_user
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account_info.del_flag
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account_info.sub_account_id
     *
     * @return the value of tb_account_info.sub_account_id
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public String getSubAccountId() {
        return subAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account_info.sub_account_id
     *
     * @param subAccountId the value for tb_account_info.sub_account_id
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public void setSubAccountId(String subAccountId) {
        this.subAccountId = subAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account_info.account_id
     *
     * @return the value of tb_account_info.account_id
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account_info.account_id
     *
     * @param accountId the value for tb_account_info.account_id
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account_info.account_phone
     *
     * @return the value of tb_account_info.account_phone
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public String getAccountPhone() {
        return accountPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account_info.account_phone
     *
     * @param accountPhone the value for tb_account_info.account_phone
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public void setAccountPhone(String accountPhone) {
        this.accountPhone = accountPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account_info.sub_account_type
     *
     * @return the value of tb_account_info.sub_account_type
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public String getSubAccountType() {
        return subAccountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account_info.sub_account_type
     *
     * @param subAccountType the value for tb_account_info.sub_account_type
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public void setSubAccountType(String subAccountType) {
        this.subAccountType = subAccountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account_info.account_status
     *
     * @return the value of tb_account_info.account_status
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public String getAccountStatus() {
        return accountStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account_info.account_status
     *
     * @param accountStatus the value for tb_account_info.account_status
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public void setAccountStatus(String accountStatus) {
        this.accountStatus = accountStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account_info.create_time
     *
     * @return the value of tb_account_info.create_time
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account_info.create_time
     *
     * @param createTime the value for tb_account_info.create_time
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account_info.create_user
     *
     * @return the value of tb_account_info.create_user
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account_info.create_user
     *
     * @param createUser the value for tb_account_info.create_user
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account_info.update_time
     *
     * @return the value of tb_account_info.update_time
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account_info.update_time
     *
     * @param updateTime the value for tb_account_info.update_time
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account_info.update_user
     *
     * @return the value of tb_account_info.update_user
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account_info.update_user
     *
     * @param updateUser the value for tb_account_info.update_user
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account_info.del_flag
     *
     * @return the value of tb_account_info.del_flag
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account_info.del_flag
     *
     * @param delFlag the value for tb_account_info.del_flag
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }
}