package com.sangtao.model;

import java.util.Date;

public class Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.account_id
     *
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    private String accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.account_name
     *
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    private String accountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.account_pwd
     *
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    private String accountPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.user_address
     *
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    private String userAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.province
     *
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.city
     *
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.account_type
     *
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    private String accountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.create_time
     *
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.create_user
     *
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.update_time
     *
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.update_user
     *
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.del_flag
     *
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.account_id
     *
     * @return the value of tb_account.account_id
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.account_id
     *
     * @param accountId the value for tb_account.account_id
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.account_name
     *
     * @return the value of tb_account.account_name
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.account_name
     *
     * @param accountName the value for tb_account.account_name
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.account_pwd
     *
     * @return the value of tb_account.account_pwd
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    public String getAccountPwd() {
        return accountPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.account_pwd
     *
     * @param accountPwd the value for tb_account.account_pwd
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    public void setAccountPwd(String accountPwd) {
        this.accountPwd = accountPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.user_address
     *
     * @return the value of tb_account.user_address
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.user_address
     *
     * @param userAddress the value for tb_account.user_address
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.province
     *
     * @return the value of tb_account.province
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.province
     *
     * @param province the value for tb_account.province
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.city
     *
     * @return the value of tb_account.city
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.city
     *
     * @param city the value for tb_account.city
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.account_type
     *
     * @return the value of tb_account.account_type
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.account_type
     *
     * @param accountType the value for tb_account.account_type
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.create_time
     *
     * @return the value of tb_account.create_time
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.create_time
     *
     * @param createTime the value for tb_account.create_time
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.create_user
     *
     * @return the value of tb_account.create_user
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.create_user
     *
     * @param createUser the value for tb_account.create_user
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.update_time
     *
     * @return the value of tb_account.update_time
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.update_time
     *
     * @param updateTime the value for tb_account.update_time
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.update_user
     *
     * @return the value of tb_account.update_user
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.update_user
     *
     * @param updateUser the value for tb_account.update_user
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.del_flag
     *
     * @return the value of tb_account.del_flag
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.del_flag
     *
     * @param delFlag the value for tb_account.del_flag
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }
}