package com.sangtao.model;

import java.util.Date;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.role_id
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.role_name
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.role_type
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    private String roleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.create_time
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.create_user
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.update_time
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.update_user
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.del_flag
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.role_id
     *
     * @return the value of tb_role.role_id
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.role_id
     *
     * @param roleId the value for tb_role.role_id
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.role_name
     *
     * @return the value of tb_role.role_name
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.role_name
     *
     * @param roleName the value for tb_role.role_name
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.role_type
     *
     * @return the value of tb_role.role_type
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public String getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.role_type
     *
     * @param roleType the value for tb_role.role_type
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public void setRoleType(String roleType) {
        this.roleType = roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.create_time
     *
     * @return the value of tb_role.create_time
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.create_time
     *
     * @param createTime the value for tb_role.create_time
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.create_user
     *
     * @return the value of tb_role.create_user
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.create_user
     *
     * @param createUser the value for tb_role.create_user
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.update_time
     *
     * @return the value of tb_role.update_time
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.update_time
     *
     * @param updateTime the value for tb_role.update_time
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.update_user
     *
     * @return the value of tb_role.update_user
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.update_user
     *
     * @param updateUser the value for tb_role.update_user
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.del_flag
     *
     * @return the value of tb_role.del_flag
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.del_flag
     *
     * @param delFlag the value for tb_role.del_flag
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }
}