package com.sangtao.model;

import java.util.Date;

public class RoleResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_role_resource.role_id
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_role_resource.resource_id
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    private String resourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_role_resource.create_time
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_role_resource.create_user
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_role_resource.update_time
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_role_resource.update_user
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_role_resource.del_flag
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_role_resource.role_id
     *
     * @return the value of tr_role_resource.role_id
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_role_resource.role_id
     *
     * @param roleId the value for tr_role_resource.role_id
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_role_resource.resource_id
     *
     * @return the value of tr_role_resource.resource_id
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_role_resource.resource_id
     *
     * @param resourceId the value for tr_role_resource.resource_id
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_role_resource.create_time
     *
     * @return the value of tr_role_resource.create_time
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_role_resource.create_time
     *
     * @param createTime the value for tr_role_resource.create_time
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_role_resource.create_user
     *
     * @return the value of tr_role_resource.create_user
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_role_resource.create_user
     *
     * @param createUser the value for tr_role_resource.create_user
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_role_resource.update_time
     *
     * @return the value of tr_role_resource.update_time
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_role_resource.update_time
     *
     * @param updateTime the value for tr_role_resource.update_time
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_role_resource.update_user
     *
     * @return the value of tr_role_resource.update_user
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_role_resource.update_user
     *
     * @param updateUser the value for tr_role_resource.update_user
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_role_resource.del_flag
     *
     * @return the value of tr_role_resource.del_flag
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_role_resource.del_flag
     *
     * @param delFlag the value for tr_role_resource.del_flag
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }
}