package com.sangtao.model;

import java.util.Date;

public class SysResources {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.sys_resource_id
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    private String sysResourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.resource_name
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    private String resourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.create_time
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.create_user
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.update_time
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.update_user
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.del_flag
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.sys_resource_id
     *
     * @return the value of sys_resources.sys_resource_id
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public String getSysResourceId() {
        return sysResourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.sys_resource_id
     *
     * @param sysResourceId the value for sys_resources.sys_resource_id
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public void setSysResourceId(String sysResourceId) {
        this.sysResourceId = sysResourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.resource_name
     *
     * @return the value of sys_resources.resource_name
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.resource_name
     *
     * @param resourceName the value for sys_resources.resource_name
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.create_time
     *
     * @return the value of sys_resources.create_time
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.create_time
     *
     * @param createTime the value for sys_resources.create_time
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.create_user
     *
     * @return the value of sys_resources.create_user
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.create_user
     *
     * @param createUser the value for sys_resources.create_user
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.update_time
     *
     * @return the value of sys_resources.update_time
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.update_time
     *
     * @param updateTime the value for sys_resources.update_time
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.update_user
     *
     * @return the value of sys_resources.update_user
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.update_user
     *
     * @param updateUser the value for sys_resources.update_user
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.del_flag
     *
     * @return the value of sys_resources.del_flag
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.del_flag
     *
     * @param delFlag the value for sys_resources.del_flag
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }
}