package com.sangtao.dao;

import com.sangtao.model.Account;
import java.util.List;

public interface AccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_account
     *
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    int deleteByPrimaryKey(String accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_account
     *
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_account
     *
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    Account selectByPrimaryKey(String accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_account
     *
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    List<Account> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_account
     *
     * @mbg.generated Fri Nov 29 19:32:08 CST 2019
     */
    int updateByPrimaryKey(Account record);
}