package com.sangtao.dao;

import com.sangtao.model.Role;
import java.util.List;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    int deleteByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    Role selectByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    List<Role> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    int updateByPrimaryKey(Role record);
}