package com.sangtao.dao;

import com.sangtao.model.RoleResource;
import java.util.List;

public interface RoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_role_resource
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    int insert(RoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_role_resource
     *
     * @mbg.generated Fri Nov 29 11:17:43 CST 2019
     */
    List<RoleResource> selectAll();
}